spring.application.name=VolunteerManagementApp
server.port =8082

#################################################
# DATABASE
#################################################

spring.datasource.url=jdbc:postgresql://localhost:5432/volunteer_management_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

#################################################
# JPA / HIBERNATE
#################################################

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

#Show SQL commands on the IDE console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=this-is-crc-super-jesus-generation
jwt.expiration-ms= 3600000 #an hour